version: '3.8'

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=cms
      - POSTGRES_DB=cmsdb
      - POSTGRES_PASSWORD=${CMSDB_PASSWORD}
    volumes:
      - cmsdb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cms -d cmsdb"]
      interval: 5s
      timeout: 2s
      retries: 2
    networks:
      - cms-backend
    restart: unless-stopped

  taskbuilder:
    image: cms-taskbuilder
    build:
      context: ./docker/taskbuilder
      dockerfile: Dockerfile
    privileged: true

  cms-services:
    image: cms-services
    build:
      context: ./docker/cms-services
      dockerfile: Dockerfile
    entrypoint: ["wait-for-it", "db:5432", "-t", "30", "--",
                 "/init"]
    networks:
      - cms-backend
      - cms-frontend
    depends_on:
      - db
    restart: unless-stopped

  web:
    image: 1.23-bullseye
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - cms-frontend
    restart: unless-stopped

networks:
  cms-backend:
  cms-frontend:

volumes:
  cmsdb-data:
