version: '3.8'

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=cmsuser
      - POSTGRES_DB=cmsdb
      - POSTGRES_PASSWORD=${CMS_DB_PASSWORD}
    volumes:
      - cmsdb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cmsuser -d cmsdb"]
      interval: 5s
      timeout: 2s
      retries: 2
    networks:
      - cms-backend
    restart: unless-stopped

  taskbuilder:
    image: cms-taskbuilder
    build:
      context: ./docker/taskbuilder
      dockerfile: Dockerfile
    privileged: true

  cms-services:
    image: cms-services
    environment:
      - CONTEST_ID=${CMS_CONTEST_ID}
    build:
      context: ./docker/cms-services
      dockerfile: Dockerfile
    entrypoint: ["wait-for-it", "db:5432", "-t", "30", "--",
                 "/init"]
    volumes:
      - ./docker/cms-services/configs/cms.conf:/usr/local/etc/cms.conf:ro
      - ./docker/cms-services/configs/cms.ranking.conf:/usr/local/etc/cms.ranking.conf:ro
    networks:
      - cms-backend
      - cms-frontend
    depends_on:
      - db
    restart: unless-stopped

  web:
    image: nginx:1.23-bullseye
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/configs/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - cms-frontend
    restart: unless-stopped

networks:
  cms-backend:
  cms-frontend:

volumes:
  cmsdb-data:
