#!/command/with-contenv bash

if $IMPORT_CONTEST; then
  cmsImportUser --loader italy_yaml --all /home/cmsuser/contest/
  cmsImportContest --loader italy_yaml --import-tasks /home/cmsuser/contest/
fi

exit 0
